services:
  postgres:
    image: postgres:18-alpine
    container_name: game-catalog-pg
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: game_catalog
    ports:
      - "127.0.0.1:5434:5432"
    volumes:
      - game-catalog-pg-data:/var/lib/postgresql
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  game-catalog-pg-data:
